# Generated by Django 2.1 on 2018-08-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16)),
                ('exec_date', models.DateTimeField(verbose_name='date executed')),
                ('buy_or_sell', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=4)),
                ('open_or_close', models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='open', max_length=5)),
                ('instrument', models.CharField(choices=[('call', 'Call'), ('put', 'Put'), ('stock', 'Stock'), ('fut', 'Futures')], default='call', max_length=5)),
                ('quantity', models.PositiveIntegerField()),
                ('execution_price', models.FloatField()),
                ('execution_fees', models.FloatField(default=0)),
                ('expiration_date', models.DateTimeField(null=True, verbose_name='expiration')),
                ('margin', models.FloatField(null=True)),
                ('underlying_price', models.FloatField(null=True)),
            ],
        ),
    ]
